
[General]
	#The number of minutes until you get tired. 20 minutes is one day-night cycle. (default: 40.0)
	minutes_until_tired = 40.0
	#If you will die from exhaustion or remain on one heart. (default: True)
	die_from_exhaustion = true
	#PLEASE DONT CHANGE! Number of ticks a phase should last. (default: 6000.0)
	phase_time_ticks = 6000.0
	#Prevent phantoms to spawn by vanilla gamerule. (default: False)
	no_phantoms = false

