name = "Acid Rain"
author = "VoltalyBee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6a2e081c37ce8d606494390e7f874c5f5d864e42a9bfbb50fed7dcec7cb33b3"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
