name = "Acid Rain"
author = "VoltalyBee"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14478a33cb6504a90904d46496fd819e94d3d5786c8e8836c0877d7c4c928274"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
