name = "Acid Rain"
author = "VoltalyBee"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b6176e9e4a5854c5fcc970360911646b6cfbcdf26512b905a250bfb720a1ab9"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
